name: Deploy Production to Beget

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: rabota19vk.beget.tech
          username: rabota19vk_timowa
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/24it.biz

            git config --global --add safe.directory /home/r/rabota19vk/24it.biz

            git fetch origin
            git reset --hard origin/master

            composer install \
              --no-interaction \
              --prefer-dist \
              --no-dev \
              --optimize-autoloader

            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize

            npm ci
            npm run build
